spring:
  profiles:
    active: test
  application:
    name: firends-mate
  redis:
    database: 0
    host: 43.138.34.196
    port: 6379
    password: Mjw20021103
  #swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # DataSource Config
  datasource:
    username: root
    password: "021103"
    url: jdbc:mysql://localhost:3306/friends_mate?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
server:
  port: 8088
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
